# Perform link check on all markdown files
name: Doc Link Checker

on:
  push:

jobs:
  markdown-link-check:
    timeout-minutes: 50
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        if: github.ref == 'refs/heads/master'
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'no'
          config-file: .github/workflows/doc-link-check.json
          base-branch: ${{ github.base_ref }}
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        if: github.ref != 'refs/heads/master'
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: .github/workflows/doc-link-check.json
          base-branch: ${{ github.base_ref }}
