# Perform link check on all markdown files
# Add any custom exclusions to doc-link-check.json

name: Doc Link Checker

on:
  push:

jobs:
  markdown-link-check:
    timeout-minutes: 50
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # check all files on master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        if: github.ref == 'refs/heads/master'
        with:
          use-quiet-mode: 'yes'
          check-modified-files-only: 'no'
          config-file: .github/workflows/doc-link-check.json
      # check changed files for branches
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        if: github.ref != 'refs/heads/master'
        with:
          use-quiet-mode: 'yes'
#          check-modified-files-only: 'yes' todo: revert
          config-file: .github/workflows/doc-link-check.json
